# Simple workflow for deploying static content to GitHub Pages
name: Deploy Frontend to Pages

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      - name: Build
        run: pnpm run build --filter web
        env:
          VITE_PUBLIC_API_DOMAIN: "gooplancton.is-a.dev/microservichess-api"
      - name: Setup Pages
        uses: actions/configure-pages@v3
        env:
          VITE_PUBLIC_API_DOMAIN: "gooplancton.is-a.dev/microservichess-api"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './apps/web/dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        env:
          VITE_PUBLIC_API_DOMAIN: "gooplancton.is-a.dev/microservichess-api"
